### ISSUE TITLE
[Feat] - Match increase

### ISSUE THREAD

**Issue by nuneeez** [Design-Under-Konstruction-Studio/Space-Parrrty#11]
O jogador poderá aumentar o match ao posicionar um tile no local onde outro match ainda está em execução (durante a janela de tempo do match).

**Comment by Trosdan** [comment]
@nuneeez essa feature vai ser implementada nesse Pack.

**Comment by nuneeez** [comment]
@Trosdan @pinechain não tô curtindo essa ideia de poder aumentar o match durante outro match. Acho melhor colocar essa atividade de volta no Backlog, e quando acabarmos de fechar a gameplay, posso tentar rever esse conceito. Por hora, acredito que não vá se encaixar.

**Comment by Trosdan** [comment]
Fechando Issue
