### ISSUE TITLE
[Feat] - Match chain v1

### ISSUE THREAD

**Issue by nuneeez** [Design-Under-Konstruction-Studio/Space-Parrrty#12]
Em uma breve janela de tempo durante ou após ser feito um match, quanto maior o número de matches simultâneos, maior será o encadeamento. Isso irá definir qual obstáculo irá ser criado para os oponentes.

**Comment by pinechain** [comment]
O obstáculo gerado pelo encadeamento está descrito em #6.

**Comment by Trosdan** [comment]
Dividir Match chain em duas versões
v1: Calcular pontuação
v2: Integração com obstaculos
