### ISSUE TITLE
[Bug] - Board finaliza execução mesmo quando o board não alcança o topo da tela

### ISSUE THREAD

**Issue by pinechain** [Design-Under-Konstruction-Studio/Space-Parrrty#2]
**Contexto**
Branch: feature/powers
Cena: Game
Input: qualquer

**Passos para reproduzir o problema**
1. No prefab Player, mude o tamanho inicial do board para 5x2 (ilustrado no anexo);
2. Inicie a simulação;
3. Mude o estado do Board para "Loading";
4. Aguarde até o Board criar uma nova linha.

**Comportamento esperado**
O jogo deve continuar executando, visto que o Board não alcançou o topo da tela.

**Comportamento obtido**
O Board mudou o estado para "Finish", encerrando a execução do jogo.

**Screenshots**
Mudança do tamanho inicial do board
![image](https://user-images.githubusercontent.com/47357348/91481583-0faf7580-e87b-11ea-8e9d-e048a5bfa20e.png)

**Comment by pinechain** [comment]
Comentário para testar o webhook.

**Comment by Trosdan** [comment]
Realizei um Testa na develop apos ter feito alguma correções do dia 26/08/2020, ele so terminou o game apos o board bate o topo

![image](https://user-images.githubusercontent.com/27647447/91501613-6bd6c180-e89c-11ea-839e-80c2ff730be6.png)

**Comment by pinechain** [comment]
> Realizei um Testa na develop apos ter feito alguma correções do dia 26/08/2020, ele so terminou o game apos o board bate o topo

Após esse comentário, fui investigar a diferença entre a develop e a feature/powers e descobri que o erro estava no método checkTileAtTop() - mais especificamente, em uma alteraçãoque realizei na esperança de remover um laço desnecessário do código.

Reverti a mudança para a implementação presente na develop, mas isso revelou um ponto para se observar. O array 2D que armazena as informações dos tiles aparenta não ser limpo em momento algum. Se isso realmente estiver acontecendo, pode apresentar problemas de performance em partidas mais longas. Sugiro investigar esse ponto em outra issue.

Problema resolvido.
